services:
  - type: web
    name: industrial-monitoring-api
    runtime: node
    region: oregon
    plan: free

    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/server.js

    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false